# Generated by Django 3.2.9 on 2021-11-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Question', models.CharField(max_length=200)),
                ('pred', models.TextField(max_length=500)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
