# Generated by Django 3.1 on 2021-11-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('docid', models.CharField(max_length=32)),
                ('question', models.CharField(max_length=512)),
                ('pred', models.CharField(max_length=1024)),
                ('content_text', models.TextField()),
                ('createtime', models.DateTimeField()),
            ],
            options={
                'db_table': 't_b_API_Log',
            },
        ),
    ]
